name: Black Code Formatter Check

"on":
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: l
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Black Code Formatter Check
        uses: psf/black@stable
